[package]
name = "microservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.17"
hyper = "0.11.7"
net2 = "0.2.31"
tokio-core = "0.1.10"
num_cpus = "1.0"
