[package]
name = "mylocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zookeeper = "0.7.0"
env_logger = "0.10.0"
uuid = { version = "1.3.4", features = ["v4"] }

[dev-dependencies]
